import {I18n} from "i18n-js";


const translations = {
  'en-us': {
    auth_title: "Sign In",
    user: "User",
    sign_in: "Log in",
    password: "Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    interface_language: "Select language",
    login_failed: "Invalid username or password",
    geozones: "Geozones",
    objects: "Objects",
    drivers: "Drivers",
    map: "Map",
    events: "Events",
    gas: "Fuel",
    services: "Services",
    settings: "Settings",
    home_footer: "Full version",
    profile: "My profile",
    user_counter: "Users counter",
    object_counter: "Total Objects",
    user_list: "Users list",
    log_out: "Log out",
    search: "Search",
    security: "Security",
    company_name: "Company name",
    phone_number: "Phone number",
    email_address: "Email address",
    contacts: "Contacts",
    address: "Address",
    save: "Save",
    default_map: "Default Map",
    measuring_system: "Measure system",
    only_with_engines: "Only objects with the engine on:",
    only_objects: "Only objects with state:",
    only_with_states: "Only objects with status:",
    filters: "Filters",
    reset_filters: "Reset filters",
    empty_list: "Empty list",
    on: "On",
    off: "Off",
    online: "Online",
    offline: "Offline",
    speed_text: "km/h",
    info: "Info",
    roads: "Route",
    parking: "Parking",
    report: "Report",
    photo: "Photo",
    power: "Power",
    engine: "Engine",
    mileage: "Mileage",
    engine_hours: "Engine hours",
    km: "km",
    hours: "hours",
    send_command: "Send command",
    create_command: "Create command",
    select_interval: "Select interval",
    today: "Today",
    yesterday: "Yesterday",
    this_week: "This week",
    this_month: "This month",
    previous_month: "Previous month",
    date: "Date",
    duration: "Duration",
    station: "Station",
    pump: "Pump",
    fuel_amount: "Refueled",
    vehicle: "Vehicle",
    limit: "Limit",
    object: "Object",
    send_command_by_sms: "Send command by SMS",
    custom_command: "Custom command",
    typed_command: "Typed command",
    from: 'From',
    to: 'To',
    total: 'Total',
    summary_report: "Summary report",
    fuel_report: "Fuel report",
    fuel_consumption: "Fuel consumption",
    level_at_the_beginning: "Start Fuel Level",
    level_at_the_ending: "Level at the end",
    consumption_for_100_km: "Consumption for 100 km",
    consumption_for_one_hour: "Consumption for 1 hour",
    idle_consumption: "Idle consumption",
    consumption_on_the_move: "Consumption on move",
    total_refills: "Total refills",
    total_drains: "Total drains",
    fuel: "Fuel",
    time: "Time",
    idle: "Idle time",
    drive: "Driving",
    fueling: "Fueling",
    drain: "Drain",
    volume: "Volume",
    report_interval: "Report interval",
    general: "General",
    max_speed: "Max speed",
    average_speed: "Average speed",
    speed: "Speed",
    l: "l",
    number_of_violations: "Number of violations",
    fines: "Fines",
    only_important: "Only important",
    all: "All",
    in_groups: "In groups",
    available_speed: "Speed limit",
    zone_type: "Zone type",
    yes: "Yes",
    no: "No",
    only_current_type: "Only current type",
    polygon: "Polygon",
    polyline: "Polyline",
    point: "Point",
    apply: "Apply",
    error_400: 'Bad Request',
    error_403: 'Forbidden',
    error_401: 'Unauthorized',
    error_404: 'Not Found',
    error_500: 'Internal Server Error',
    refresh_interval: 'Refresh interval, sec.',
    select_item: 'Select an item',
    in_move: 'Driving',
    parked: 'Parked',
    min_drive_min: 'Minimum drive, minute',
    min_drive_km: 'Minimum drive, KM',
    min_parking_min:  'Minimum parking, min.',
    general_report: 'General report',
    calendar_alert: 'The selected range exceeds 30 days. Please select a range less than 31 days',
  },
  'ru-ru': {
    auth_title: "Авторизация",
    user: "Пользователь",
    sign_in: "Войти",
    password: "Пароль",
    new_password: "Новый пароль",
    confirm_password: "Подтверждение пароля",
    interface_language: "Язык интерфейса",
    login_failed: "Не верный логин или пароль",
    geozones: "Геозоны",
    objects: "Объекты",
    drivers: "Водители",
    map: "Карта",
    events: "События",
    gas: "АЗС",
    services: "Сервисы",
    settings: "Настройки",
    home_footer: "Полная версия",
    profile: "Ваш профиль",
    user_counter: "Колличество пользователей",
    object_counter: "Колличество объектов",
    user_list: "Список пользователей",
    log_out: "Выйти",
    search: "Поиск",
    security: "Безопасность",
    company_name: "Название фирмы",
    phone_number: "Номер телефона",
    email_address: "Электронная почта",
    contacts: "Контакт",
    address: "Адрес",
    save: "Сохранить",
    default_map: "Карта по умолчанию",
    measuring_system: "Система измерения",
    only_with_engines: "Только объекты с включенным двигателем:",
    only_objects: "Отобразить только объекты:",
    only_with_states: "Отобразить только объекты со статусом:",
    filters: "Фильтры",
    reset_filters: "Сбросить фильтры",
    empty_list: "Пустой список",
    on: "Вкл",
    off: "Выкл",
    online: "В сети",
    offline: "Не в сети",
    speed_text: "км/ч",
    info: "Инфо",
    roads: "Поездки",
    parking: "Парковки",
    report: "Отчеты",
    photo: "Фото",
    power: "Мощность",
    engine: "Двигатель",
    mileage: "Пробег",
    engine_hours: "Моточасы",
    km: "км",
    hours: "часов",
    send_command: "Отпр. команду",
    create_command: "Создать задачу",
    select_interval: "Выберите интервал",
    today: "Сегодня",
    yesterday: "Вчера",
    this_week: "Неделя",
    this_month: "Этот месяц",
    previous_month: "Прошлый месяц",
    date: "Дата",
    duration: "Продолжительность",
    station: "Станция",
    pump: "Насос",
    fuel_amount: "Количество",
    vehicle: "Кому",
    limit: "Лимит",
    object: "Объект",
    send_command_by_sms: "Отправлять команды СМС сообщениями",
    custom_command: "Своя команда",
    typed_command: "Введите команду",
    from: 'От',
    to: 'До',
    total: "Итого",
    summary_report: "Суммарный отчет",
    fuel_report: "Отчет по топливу",
    fuel_consumption: "Расход топлива",
    level_at_the_beginning: "Уровень в начале",
    level_at_the_ending: "Уровень в конце",
    consumption_for_100_km: "Расход на 100 км",
    consumption_for_one_hour: "Расход на 1 час",
    idle_consumption: "Расход в простое",
    consumption_on_the_move: "Расход в движении",
    total_refills: "Всего заправок",
    total_drains: "Всего сливов",
    fuel: "Топливо",
    time: "Время",
    idle: "Холостой",
    drive: "Воджение",
    fueling: "Заправка",
    drain: "Слив",
    volume: "Объем",
    report_interval: "Отчет за период",
    general: "Основное",
    max_speed: "Максимальная скорость",
    average_speed: "Средняя скорость",
    speed: "Средняя",
    l: "л",
    number_of_violations: "Количество нарушений",
    fines: "Штрафы",
    only_important: "Только важные",
    all: "Все",
    in_groups: "В группах",
    available_speed: "Допустимая скорость",
    zone_type: "Тип зоны",
    yes: "Да",
    no: "Нет",
    only_current_type: "Только выбранный тип",
    polygon: "Многоугольник",
    polyline: "Линия",
    point: "Точка",
    apply: "Применить",
    error_400: 'Неверный запрос',
    error_403: 'Доступ к ресурсу запрещен',
    error_401: 'Неавторизованный запрос',
    error_404: 'Ресурс не найден',
    error_500: 'Внутренняя ошибка сервера',
    refresh_interval: 'Интервал обновления, сек.',
    select_item: 'Выберите',
    in_move: 'В движение',
    parked: 'В парковке',
    min_drive_min: 'Мин. вождения, минут',
    min_drive_km: 'Мин. вождения, км.',
    min_parking_min:  'Минимальная парковка, мин.',
    general_report: 'Сводный отчет',
    calendar_alert: 'Выбранный диапазон превышает 30 дней. Пожалуйста, выберите диапазон менее 31 дня',
  },
  'tr-tr': {
    auth_title: "Giriş",
    user: "Kullanıcı",
    sign_in: "Oturumu aç",
    password: "Şifre",
    new_password: "Yeni şifre",
    confirm_password: "Şifreyi onayla",
    interface_language: "Dil seçimi",
    login_failed: "Kullanıcı veya parola yalnış",
    geozones: "Bölgeler",
    objects: "Araçlar",
    drivers: "Sürücüler",
    map: "Harita",
    events: "Uyarılar",
    gas: "Petrol",
    services: "Servis",
    settings: "Ayarlar",
    home_footer: "Desktop versiyonu",
    profile: "Profilim",
    user_counter: "Kullanıcı sayı",
    object_counter: "Araç sayı",
    user_list: "Kullanıcı listesi",
    log_out: "Çık",
    search: "Ara",
    security: "Güvenlik",
    company_name: "Şirket ismi",
    phone_number: "Telefon numarası",
    email_address: "Email",
    contacts: "Kontakt",
    address: "Adres",
    save: "Kayd et",
    default_map: "Harita",
    measuring_system: "Olçü birimi",
    only_with_engines: "Motoru çalışan araçlar:",
    only_objects: "Yolda giden araçlar:",
    only_with_states: "Araç statusunu göre:",
    filters: "Filtreler",
    reset_filters: "Filtreleri sıfırla",
    empty_list: "Boş liste",
    on: "Açk",
    off: "Kap.",
    online: "Onlayn",
    offline: "Oflayn",
    speed_text: "km/s",
    info: "İnfo",
    roads: "Rota",
    parking: "Park",
    report: "Rapor",
    photo: "Resim",
    power: "Elektrik",
    engine: "Motor",
    mileage: "Odometre",
    engine_hours: "Мotor saatı",
    km: "km",
    hours: "saat",
    send_command: "Komut gönder",
    create_command: "Görev yarat",
    select_interval: "Aralığı seç",
    today: "Bugün",
    yesterday: "Dün",
    this_week: "Bu hafta",
    this_month: "Bu ay",
    previous_month: "Geçen ay",
    date: "Zaman",
    duration: "Süre",
    station: "İstasyon",
    pump: "Pompa",
    fuel_amount: "Yakıt miktarı",
    vehicle: "Araç",
    limit: "Limit",
    object: "Araç",
    send_command_by_sms: "Kumotu SMS ile gönder",
    custom_command: "Yeni komut",
    typed_command: "Komutu gir",
    from: 'Baş',
    to: 'Son',
    total: "Toplam",
    summary_report: "Genel rapor",
    fuel_report: "Yakıt raporu",
    fuel_consumption: "Yakıt tüketimi",
    level_at_the_beginning: "Baş. seviye",
    level_at_the_ending: "Son seviye",
    consumption_for_100_km: "Tüketim 100 km",
    consumption_for_one_hour: "Tüketim 1 saat",
    idle_consumption: "Rölanti tüketimi",
    consumption_on_the_move: "Yolda tüketim",
    total_refills: "Toplam dolum",
    total_drains: "Toplam boşaltma",
    fuel: "Yakıt",
    time: "Zaman",
    idle: "Rölantı",
    drive: "Sürme",
    fueling: "Dolum",
    drain: "Boşaltma",
    volume: "Hacmi",
    report_interval: "Rapor aralığı",
    general: "Genel",
    max_speed: "Maksimum hız",
    average_speed: "Orta hız",
    speed: "Orta",
    l: "l",
    number_of_violations: "İhlal sayı",
    fines: "Ceza puanı",
    only_important: "Önemli",
    all: "Tüm",
    in_groups: "Qrupta",
    available_speed: "Hız limiti",
    zone_type: "Bölge tipi",
    yes: "Evet",
    no: "Hayır",
    only_current_type: "Sadece seçilmiş tip",
    polygon: "Poligon",
    polyline: "Hat",
    point: "Daire",
    apply: "Uygula",
    error_400: 'Uygulama hatası',
    error_403: 'Kaynağa erişim reddedildi',
    error_401: 'Yetkisiz istek',
    error_404: 'Kaynak bulunamadı',
    error_500: 'Server hatası',
    refresh_interval: 'Güncelleme aralığı, san.',
    select_item: 'Listeden seç',
    in_move: 'Gidiyor',
    parked: 'Park halinde',
    min_drive_min: 'Minimum yol, dak.',
    min_drive_km: 'Minimum yol, km.',
    min_parking_min:  'Minimum park, dak.',
    general_report: 'Genel rapor',
    calendar_alert: 'Seçilen aralık 30 günü aşıyor. Lütfen 31 günden kısa bir aralık seçin',
  },
  'az-latn-az': {
    auth_title: "Sisteme giriş",
    user: "İstifadəçi",
    sign_in: "Giriş",
    password: "Şifrə",
    new_password: "Yeni şifrə",
    confirm_password: "Şifrəni təkrarla",
    interface_language: "Dil seçimi",
    login_failed: "İstifadəçi və ya şifrə düz deyil",
    geozones: "Zonalar",
    objects: "Maşınlar",
    drivers: "Sürücülər",
    map: "Xəritə",
    events: "Alarmlar",
    gas: "AZS",
    services: "Servis",
    settings: "Ayarlar",
    home_footer: "Desktop versiyası",
    profile: "Profilim",
    user_counter: "istifadəçi sayı",
    object_counter: "Maşın sayı",
    user_list: "İstifadəçi siyahısı",
    log_out: "Çıx",
    search: "Axtar",
    security: "Güvənlik",
    company_name: "Şirket adı",
    phone_number: "Telefon nömrəsi",
    email_address: "Email",
    contacts: "Kontakt",
    address: "Adres",
    save: "Yadda saxla",
    default_map: "Xəritə",
    measuring_system: "Olçü vahidi",
    only_with_engines: "Motoru işləyən maşınlar:",
    only_objects: "Yolda gedən maşınlar:",
    only_with_states: "Maşın statusunu görə:",
    filters: "Filterlər",
    reset_filters: "Filtreri sıfırla",
    empty_list: "Boş siyahı",
    on: "Açk",
    off: "Bağ.",
    online: "Onlayn",
    offline: "Oflayn",
    speed_text: "km/s",
    info: "İnfo",
    roads: "Marşrut",
    parking: "Park",
    report: "Hesabat",
    photo: "Şəkil",
    power: "Elektrik",
    engine: "Motor",
    mileage: "Odometrə",
    engine_hours: "Мotor saatı",
    km: "km",
    hours: "saat",
    send_command: "Komanda gönder",
    create_command: "Görəv yarat",
    select_interval: "İntervalı seç",
    today: "Bugün",
    yesterday: "Dünən",
    this_week: "Bu həftə",
    this_month: "Bu ay",
    previous_month: "Geçən ay",
    date: "Zaman",
    duration: "Müddət",
    station: "AZS",
    pump: "Nasos",
    fuel_amount: "Yanacaq miqdarı",
    vehicle: "Maşın",
    limit: "Limit",
    object: "Maşın",
    send_command_by_sms: "Komandanı SMS ile göndər",
    custom_command: "Yeni komanda",
    typed_command: "Komandanı gir",
    from: 'Baş',
    to: 'Son',
    total: "Toplam",
    summary_report: "Gənəl hesabat",
    fuel_report: "YDM hesabatı",
    fuel_consumption: "YDM tüketimi",
    level_at_the_beginning: "Baş. seviyə",
    level_at_the_ending: "Son seviyə",
    consumption_for_100_km: "Sərfiyat 100 km",
    consumption_for_one_hour: "Sərfiyat 1 saat",
    idle_consumption: "Boş sərfiyat",
    consumption_on_the_move: "Yolda sərfiyat",
    total_refills: "Toplam dolum",
    total_drains: "Toplam boşaltma",
    fuel: "Yanacaq",
    time: "Zaman",
    idle: "Boş işləmə",
    drive: "Sürmə",
    fueling: "Dolum",
    drain: "Boşaltma",
    volume: "Miqdar",
    report_interval: "Hesabat intervalı",
    general: "Gənəl",
    max_speed: "Maksimum sürət",
    average_speed: "Orta sürət",
    speed: "Orta",
    l: "l",
    number_of_violations: "Qayda pozuntuları",
    fines: "Cəza balı",
    only_important: "Vacib",
    all: "Hamısı",
    in_groups: "Qrupda",
    available_speed: "Sürət limiti",
    zone_type: "Zona tipi",
    yes: "Hə",
    no: "Yox",
    only_current_type: "Sadəce seçilmiş tip",
    polygon: "Poligon",
    polyline: "Xətt",
    point: "Nöqtə",
    apply: "Yenilə",
    error_400: 'Uygulama xətası',
    error_403: 'Resursa giriş qadağandır',
    error_401: 'İcazəsiz sorğu',
    error_404: 'Resurs tapılmadı',
    error_500: 'Server xətası',
    refresh_interval: 'Yeniləmə intervalı, san.',
    select_item: 'Siyahıdan seç',
    in_move: 'Gedir',
    parked: 'Dayanıb',
    min_drive_min: 'Minimum yol, dəq.',
    min_drive_km: 'Minimum yol, km.',
    min_parking_min:  'Minimum park, dəq.',
    general_report: 'Gənəl hesabat',
    calendar_alert: 'Seçilmiş diapazon 30 günü keçir. Zəhmət olmasa 31 gündən az bir sıra seçin',
  }
}


const i18n = new I18n(translations);
i18n.defaultLocale = "en-us"
i18n.enableFallback = true;

export default i18n
